# Generated by Django 4.0.5 on 2022-07-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name="Serialized last state of game's board.")),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('completed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsid', models.CharField(max_length=255, verbose_name='Game session id')),
                ('game_uuid', models.CharField(max_length=255, verbose_name='Game unique id')),
                ('player', models.CharField(max_length=255, verbose_name='Used player class for this game')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_games.gameboard')),
            ],
        ),
    ]
