# Generated by Django 4.0.5 on 2022-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegame',
            name='player',
        ),
        migrations.AddField(
            model_name='activegame',
            name='player_class',
            field=models.CharField(default='xcvxcvxcv', max_length=255, verbose_name='Player class for this game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activegame',
            name='player_kwargs',
            field=models.CharField(default='fgsfgsfgsf', max_length=255, verbose_name='Keyword arguments for player class'),
            preserve_default=False,
        ),
    ]
